#!/bin/bash
[ -z $OPP_ENV_VERSION ] && echo "<!> Error: This OMNeT++ installation cannot be used outside an opp_env shell." && exit 1
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/nix/store/srby6wmvg7dp454pwb6qvaxdiri38sc1-zlib-1.3.1/lib:/nix/store/41qbms27n02859ja4sc7wsd9mfp3ward-cairo-1.18.2/lib:/nix/store/42dlyn8qbxdp55gxd35xymik0nhy0hdw-gtk+3-3.24.49/lib:/nix/store/bkpj51fz88rbyjd60i6lrp0xdax1b24g-glib-2.84.1/lib:/nix/store/x8c7sj6qnmlwsi64707yjx3fn0njbc21-libsecret-0.21.7/lib:/nix/store/j48pmz97gkr8ki3b8i2xcnrr0kdxz91g-libXtst-1.2.5/lib" 
#
# Detects the platform and architecture, and starts the IDE with the right launcher
#
IDEDIR=$(cd $(dirname $0)/../ide; pwd)
PLATFORM=$(uname -sm)
LAUNCHER=opp_ide
if [ -z "${PRODUCT}" ]; then
  PRODUCT='OMNeT++'
fi

if [ "$(cd $(dirname $0)/.. && pwd)" != "$__omnetpp_root_dir" ]; then
  # source the setenv script if no environment is present or a the current environment is not pointing
  # to the directory we are present. (MUST be sourced from the installation root)
  cd $(dirname $0)/.. ; . ./setenv ; cd - >/dev/null
fi

if test ! -d $IDEDIR/configuration -a ! -d $IDEDIR/$LAUNCHER.app/Contents/Eclipse/configuration; then
  echo "The $PRODUCT IDE is not installed!"
  exit 1;
fi

echo Starting the $PRODUCT IDE...

#set default language so GCC will report errors in english. see bug #3
export LANG=en_US.UTF-8
# arguments needed to initially correctly show the default 'samples' workspace
DEFAULT_WORKSPACE_ARGS="-vmargs -Dosgi.instance.area.default=$IDEDIR/../.."
STATE_DIR=${XDG_STATE_HOME:-$HOME/.local/state}/omnetpp
mkdir -p $STATE_DIR

case $PLATFORM in
*MINGW*)
	$IDEDIR/${LAUNCHER}.exe --launcher.openFile "$@" $DEFAULT_WORKSPACE_ARGS 2>$STATE_DIR/ide-error.log &
        ;;
*Linux*)
	$IDEDIR/${LAUNCHER} --launcher.openFile "$@" $DEFAULT_WORKSPACE_ARGS 2>$STATE_DIR/ide-error.log &
        ;;
*Darwin*)
	# remove the quarantine extended bit so the IDE will not be copied to a private dir on macOS sierra and later
	xattr -d com.apple.quarantine $IDEDIR/${LAUNCHER}.app 2>/dev/null
	# add the native libs plugin to the path so executables placed there (like lldbmi2) can be executed
	IDE_NATIVE_PLUGIN_DIR=$(echo "$IDEDIR/${LAUNCHER}.app"/Contents/Eclipse/plugins/org.omnetpp.ide.nativelibs.macosx*)
	export PATH="$IDE_NATIVE_PLUGIN_DIR:$PATH"
	# starting the executable directly allows to avoid unsigned app warnings showing up
	$IDEDIR/${LAUNCHER}.app/Contents/MacOS/${LAUNCHER} --launcher.openFile "$@" $DEFAULT_WORKSPACE_ARGS 2>$STATE_DIR/ide-error.log &
        ;;
*)
	echo $PRODUCT IDE is supported only on: Linux, Windows and macOS
	exit 1
        ;;
esac
