#!/usr/bin/env python3
"""
Dynamic Per-Frame Compression Model Training

This script trains an XGBoost model on the GROUND TRUTH dataset generated by
generate_per_frame_dataset.py.

The dataset already contains the optimal compression level for each frame,
determined by exhaustive simulation sweeps. The model learns to predict this
optimal level directly from frame and network features.

Features:
  - num_users: Number of users in the cell
  - cqi: Channel Quality Indicator for the user
  - fps: Frame rate
  - frame_complexity: Frame size at max components (inherent difficulty)

Target:
  - optimal_compression_level: The Ground Truth optimal level

Usage:
    cd /home/teaching/Projects/NASCX/simu5g-1.3.0/simulations/NR/xr
    python3 train_dynamic_model.py
"""

import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, accuracy_score
from sklearn.preprocessing import StandardScaler
import joblib
from pathlib import Path

# Configuration
DATASET_PATH = Path(__file__).parent / "datasets" / "per_frame_dataset.csv"
MODEL_PATH = Path(__file__).parent / "models" / "compression_model_dynamic.joblib"
VALID_COMPRESSION_LEVELS = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80])

# Feature columns
FEATURE_COLUMNS = ['num_users', 'cqi', 'fps', 'frame_complexity']
TARGET_COLUMN = 'optimal_compression_level'


def snap_to_compression_level(pred: float) -> int:
    """Snap regression output to nearest valid compression level."""
    idx = np.abs(VALID_COMPRESSION_LEVELS - pred).argmin()
    return int(VALID_COMPRESSION_LEVELS[idx])


def main():
    print("=" * 60)
    print("DYNAMIC PER-FRAME COMPRESSION MODEL TRAINING (Supervised)")
    print("=" * 60)
    
    # Check if dataset exists
    if not DATASET_PATH.exists():
        print(f"Error: Dataset not found at {DATASET_PATH}")
        return

    # Load dataset
    print(f"\nLoading per-frame dataset from {DATASET_PATH}...")
    df = pd.read_csv(DATASET_PATH)
    print(f"Loaded {len(df)} per-frame samples")
    
    if TARGET_COLUMN not in df.columns:
        print(f"Error: Target column '{TARGET_COLUMN}' not found in dataset.")
        print("Please regenerate the dataset using the updated generate_per_frame_dataset.py script.")
        return

    # Prepare Data
    # Rename avg_cqi -> cqi to match feature convention
    if 'avg_cqi' in df.columns:
        df = df.rename(columns={'avg_cqi': 'cqi'})
    
    # Filter valid features
    # Ensure all feature columns exist
    missing_cols = [c for c in FEATURE_COLUMNS if c not in df.columns]
    if missing_cols:
        print(f"Error: Missing feature columns: {missing_cols}")
        return

    df = df[FEATURE_COLUMNS + [TARGET_COLUMN]].dropna()
    print(f"\nTraining samples after cleanup: {len(df)}")
    
    # Statistics
    print(f"\nLabel Distribution (Optimal Compression):")
    print(df[TARGET_COLUMN].value_counts().sort_index())
    
    # Prepare X and y
    X = df[FEATURE_COLUMNS].values
    y = df[TARGET_COLUMN].values
    
    # Split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )
    
    # Scale Features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    
    print(f"\nTraining features: {FEATURE_COLUMNS}")
    print(f"Training set: {len(X_train)} samples")
    print(f"Test set: {len(X_test)} samples")
    
    # Train XGBoost
    # Use sample weights? Ground truth is cleaner, but if classes are imbalanced, weights help.
    from sklearn.utils.class_weight import compute_sample_weight
    sample_weights = compute_sample_weight('balanced', y_train)
    
    print("\nTraining XGBoost Regressor...")
    model = XGBRegressor(
        n_estimators=200,
        max_depth=6,
        learning_rate=0.08,
        min_child_weight=2,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        n_jobs=-1
    )
    
    model.fit(X_train_scaled, y_train, sample_weight=sample_weights)
    print("Model trained successfully!")
    
    # Feature Importance
    print(f"\nFeature Importance:")
    if hasattr(model, 'feature_importances_'):
        for feat, imp in zip(FEATURE_COLUMNS, model.feature_importances_):
            bar = "█" * int(imp * 40)
            print(f"  {feat:20s}: {imp:.4f} {bar}")
        
    # Evaluation
    print(f"\n{'='*60}")
    print("MODEL EVALUATION (Test Set)")
    print(f"{'='*60}")
    
    y_pred_raw = model.predict(X_test_scaled)
    y_pred_snapped = np.array([snap_to_compression_level(p) for p in y_pred_raw])
    
    mae = mean_absolute_error(y_test, y_pred_snapped)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred_snapped))
    r2 = r2_score(y_test, y_pred_snapped)
    acc = accuracy_score(y_test, y_pred_snapped)
    
    print(f"MAE:  {mae:.2f}")
    print(f"RMSE: {rmse:.2f}")
    print(f"R²:   {r2:.3f}")
    print(f"Exact Accuracy: {acc*100:.1f}%")
    
    within_5 = np.mean(np.abs(y_pred_snapped - y_test) <= 5)
    print(f"Within ±5:      {within_5*100:.1f}%")
    
    # Save Model
    DATASET_PATH.parent.parent.joinpath("models").mkdir(exist_ok=True)
    
    print(f"\nSaving model to {MODEL_PATH}...")
    joblib.dump({
        'model': model,
        'scaler': scaler,
        'feature_columns': FEATURE_COLUMNS,
        'valid_compression_levels': VALID_COMPRESSION_LEVELS.tolist(),
        'model_type': 'per_frame_supervised'
    }, MODEL_PATH)
    print("Model saved successfully!")


if __name__ == "__main__":
    main()
